#spring.application.name=pruebas
#spring.datasource.url=jdbc:postgresql://localhost:5432/pruebasdb
#spring.datasource.username=postgres
#spring.datasource.password=Estefania123
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.show-sql=true

server.port=${SERVER_PORT}

spring.datasource.url=${DATABASE_HOST}
spring.datasource.username=${DB_USER}
spring.datasource.password=${PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true